In [1]:
import uproot
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
import os
import sys
import ROOT
from yaml import safe_load
from math import sqrt

Welcome to JupyROOT 6.28/10

In [2]:
# Config and yaml file must be in this directory by default
# Absolute path must be supplied for the script to work in batch mode
configPath = '/r01/lhcb/ejnw2/fcc/FCCAnalyses/examples/FCCee/flavour/B2Inv'
sys.path.append(os.path.abspath(configPath))
import config as cfg

## Check merge Ttree has worked as expect

In [3]:
merged_file_path = '/r01/lhcb/ejnw2/fcc/FCCAnalyses/examples/FCCee/flavour/B2Inv/outputs/stage2_training_old_and_incorrectBSC/full_data_merged/p8_ee_Zbb_ecm91_EvtGen_Bs2NuNu_allchunks.root'
# Create instance of uproot, we have opened the file
uproot_file = uproot.open( merged_file_path )

# Look at trees in file
print( "Trees : " , uproot_file.keys() )

tree = uproot_file['events']

# define variables we want out
branches = ['EVT_MVA1','PV_Rec_vtx_m']    

df_merged = tree.arrays(
    expressions = branches , 
  library = 'pd' ,
)


# close file
uproot_file.close()

Trees :  ['events;13', 'events;12', 'eventsProcessed;1', 'eventsSelected;1']

In [4]:
df_merged

        EVT_MVA1  PV_Rec_vtx_m
0       0.998781      5.512964
1       0.997979      6.066088
2       0.921724      8.453005
3       0.984661     11.249550
4       0.961530      9.316105
...          ...           ...
699027  0.992224      4.267108
699028  0.990926      4.287626
699029  0.990859      9.604672
699030  0.997206     17.763226
699031  0.988623      7.573144

[699032 rows x 2 columns]

In [5]:
data_folder_path = '/r01/lhcb/ejnw2/fcc/FCCAnalyses/examples/FCCee/flavour/B2Inv/outputs/stage2_training_old_and_incorrectBSC/'
list = ['p8_ee_Zbb_ecm91_EvtGen_Bs2NuNu'] #['p8_ee_Zbb_ecm91_EvtGen_Bs2NuNu','p8_ee_Zbb_ecm91_EvtGen_Bd2NuNu','p8_ee_Zbb_ecm91','p8_ee_Zcc_ecm91','p8_ee_Zss_ecm91', 'p8_ee_Zud_ecm91']
for sample in list:
    folder_path = data_folder_path+ sample
    input_files = os.listdir(folder_path)

    i=0
    for file in input_files:
        input_file_path = os.path.join(folder_path, file)
        uproot_file = uproot.open( input_file_path )

        tree = uproot_file['events']
    
        # define variables we want out
        branches = ['EVT_MVA1','PV_Rec_vtx_m']    
        
        df = tree.arrays(
            expressions = branches , 
          library = 'pd' ,
        )
        
        # close file
        uproot_file.close()
        if i==0:
            df_full = df

        else:
            df_full = pd.concat([df_full, df], axis=0)
        i+=1

In [6]:
df_full

       EVT_MVA1  PV_Rec_vtx_m
0      0.998781      5.512964
1      0.997979      6.066088
2      0.921724      8.453005
3      0.984661     11.249550
4      0.961530      9.316105
...         ...           ...
87251  0.992224      4.267108
87252  0.990926      4.287626
87253  0.990859      9.604672
87254  0.997206     17.763226
87255  0.988623      7.573144

[699032 rows x 2 columns]

In [7]:
df_full.reset_index(inplace=True,drop=True)

In [8]:
df_full

        EVT_MVA1  PV_Rec_vtx_m
0       0.998781      5.512964
1       0.997979      6.066088
2       0.921724      8.453005
3       0.984661     11.249550
4       0.961530      9.316105
...          ...           ...
699027  0.992224      4.267108
699028  0.990926      4.287626
699029  0.990859      9.604672
699030  0.997206     17.763226
699031  0.988623      7.573144

[699032 rows x 2 columns]

In [9]:
df_merged.equals(df_full)

True